Help install-tweaks find repo

diff --git a/examples/install-tweaks b/examples/install-tweaks
--- a/examples/install-tweaks
+++ b/examples/install-tweaks
@@ -1,20 +1,39 @@
 #!/bin/bash
 
+# Symlink this script somewhere in your path
+# Usage: install-tweaks SUBPACKAGENAME
+
+# git clone https://github.com/navarum/tweaks tweaks.navarum
+# (or use a version you forked)
+# ./tweaks.navarum/examples/install-tweaks
+
+BASE=$(cd $(dirname $0) && pwd)
+echo BASE=$BASE
+if [[ $BASE != */examples ]]; then
+    >&2 echo "$0: Couldn't find base directory"
+    exit 1
+fi
+
 set -e
 
-if [ -d tweaks.navarum ]; then
-    cd tweaks.navarum
-    git pull
-else
-    git clone https://github.com/navarum/tweaks tweaks.navarum
-    cd tweaks.navarum
-fi
+cd $BASE/../
+
+git pull
+
+# if [ -d tweaks.navarum ]; then
+#     cd tweaks.navarum
+#     git pull
+# else
+#     git clone https://github.com/navarum/tweaks tweaks.navarum
+#     cd tweaks.navarum
+# fi
+
 export PREFIX=$HOME/.local
 FAILED=""
 if [ $# -gt 0 ]; then
     TARGETS="$@"
 else
-    TARGETS="screen pulseaudio urxvt unison"
+    TARGETS="screen pulseaudio urxvt unison r"
 fi
 for pkg in $TARGETS; do
     ./$pkg/BUILD install || FAILED="$FAILED $pkg"
